=pod

=head1 NAME

Topics

=head1 HOWTOS

=head2 middle-of-am

How to resolve or abort an incomplete am (apply mail)

=head2 middle-of-bisect

How to continue or abort a bisection

=head2 middle-of-merge

How to resolve or abort an incomplete merge

=head2 middle-of-rebase

How to resolve or abort an incomplete rebase

=head1 MISC

=head2 refspecs

Advanced pushing and pulling: detailed control of storage

=head2 remote-urls

Format for referring to remote (and not-so-remote) repositories

=head2 revisions

Various methods for referring to revisions

=head2 staging

Marking a subset of the local changes ready for committing

=head2 storage

High level overview of how commits, tags, and branches are stored

=head1 AUTHOR

Elijah Newren

=cut
